###############################################################################
# Created by write_sdc
###############################################################################
current_design user_project_wrapper
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name io_clock_PAD -period 10.0000 
set_clock_uncertainty 0.2500 io_clock_PAD
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[0]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[10]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[11]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[12]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[13]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[14]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[15]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[16]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[17]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[18]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[19]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[1]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[20]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[21]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[22]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[23]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[24]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[25]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[26]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[27]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[28]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[29]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[2]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[30]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[31]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[32]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[33]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[34]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[35]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[36]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[37]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[38]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[39]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[3]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[40]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[41]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[42]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[43]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[44]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[45]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[46]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[47]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[48]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[49]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[4]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[50]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[51]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[52]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[53]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[54]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[55]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[56]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[57]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[58]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[59]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[5]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[60]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[61]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[62]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[63]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[64]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[65]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[66]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[67]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[68]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[69]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[6]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[70]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[71]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[7]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[8]}]
set_input_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[9]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[0]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[10]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[11]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[12]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[13]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[14]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[15]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[16]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[17]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[18]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[19]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[1]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[20]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[21]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[22]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[23]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[24]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[25]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[26]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[27]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[28]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[29]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[2]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[30]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[31]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[32]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[33]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[34]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[35]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[36]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[37]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[38]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[39]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[3]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[40]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[41]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[42]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[43]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[44]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[45]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[46]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[47]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[48]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[49]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[4]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[50]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[51]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[52]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[53]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[54]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[55]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[56]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[57]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[58]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[59]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[5]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[60]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[61]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[62]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[63]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[64]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[65]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[66]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[67]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[68]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[69]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[6]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[70]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[71]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[7]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[8]}]
set_output_delay 2.0000 -clock [get_clocks {io_clock_PAD}] -add_delay [get_ports {analog_io[9]}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0060 [get_ports {analog_io[71]}]
set_load -pin_load 0.0060 [get_ports {analog_io[70]}]
set_load -pin_load 0.0060 [get_ports {analog_io[69]}]
set_load -pin_load 0.0060 [get_ports {analog_io[68]}]
set_load -pin_load 0.0060 [get_ports {analog_io[67]}]
set_load -pin_load 0.0060 [get_ports {analog_io[66]}]
set_load -pin_load 0.0060 [get_ports {analog_io[65]}]
set_load -pin_load 0.0060 [get_ports {analog_io[64]}]
set_load -pin_load 0.0060 [get_ports {analog_io[63]}]
set_load -pin_load 0.0060 [get_ports {analog_io[62]}]
set_load -pin_load 0.0060 [get_ports {analog_io[61]}]
set_load -pin_load 0.0060 [get_ports {analog_io[60]}]
set_load -pin_load 0.0060 [get_ports {analog_io[59]}]
set_load -pin_load 0.0060 [get_ports {analog_io[58]}]
set_load -pin_load 0.0060 [get_ports {analog_io[57]}]
set_load -pin_load 0.0060 [get_ports {analog_io[56]}]
set_load -pin_load 0.0060 [get_ports {analog_io[55]}]
set_load -pin_load 0.0060 [get_ports {analog_io[54]}]
set_load -pin_load 0.0060 [get_ports {analog_io[53]}]
set_load -pin_load 0.0060 [get_ports {analog_io[52]}]
set_load -pin_load 0.0060 [get_ports {analog_io[51]}]
set_load -pin_load 0.0060 [get_ports {analog_io[50]}]
set_load -pin_load 0.0060 [get_ports {analog_io[49]}]
set_load -pin_load 0.0060 [get_ports {analog_io[48]}]
set_load -pin_load 0.0060 [get_ports {analog_io[47]}]
set_load -pin_load 0.0060 [get_ports {analog_io[46]}]
set_load -pin_load 0.0060 [get_ports {analog_io[45]}]
set_load -pin_load 0.0060 [get_ports {analog_io[44]}]
set_load -pin_load 0.0060 [get_ports {analog_io[43]}]
set_load -pin_load 0.0060 [get_ports {analog_io[42]}]
set_load -pin_load 0.0060 [get_ports {analog_io[41]}]
set_load -pin_load 0.0060 [get_ports {analog_io[40]}]
set_load -pin_load 0.0060 [get_ports {analog_io[39]}]
set_load -pin_load 0.0060 [get_ports {analog_io[38]}]
set_load -pin_load 0.0060 [get_ports {analog_io[37]}]
set_load -pin_load 0.0060 [get_ports {analog_io[36]}]
set_load -pin_load 0.0060 [get_ports {analog_io[35]}]
set_load -pin_load 0.0060 [get_ports {analog_io[34]}]
set_load -pin_load 0.0060 [get_ports {analog_io[33]}]
set_load -pin_load 0.0060 [get_ports {analog_io[32]}]
set_load -pin_load 0.0060 [get_ports {analog_io[31]}]
set_load -pin_load 0.0060 [get_ports {analog_io[30]}]
set_load -pin_load 0.0060 [get_ports {analog_io[29]}]
set_load -pin_load 0.0060 [get_ports {analog_io[28]}]
set_load -pin_load 0.0060 [get_ports {analog_io[27]}]
set_load -pin_load 0.0060 [get_ports {analog_io[26]}]
set_load -pin_load 0.0060 [get_ports {analog_io[25]}]
set_load -pin_load 0.0060 [get_ports {analog_io[24]}]
set_load -pin_load 0.0060 [get_ports {analog_io[23]}]
set_load -pin_load 0.0060 [get_ports {analog_io[22]}]
set_load -pin_load 0.0060 [get_ports {analog_io[21]}]
set_load -pin_load 0.0060 [get_ports {analog_io[20]}]
set_load -pin_load 0.0060 [get_ports {analog_io[19]}]
set_load -pin_load 0.0060 [get_ports {analog_io[18]}]
set_load -pin_load 0.0060 [get_ports {analog_io[17]}]
set_load -pin_load 0.0060 [get_ports {analog_io[16]}]
set_load -pin_load 0.0060 [get_ports {analog_io[15]}]
set_load -pin_load 0.0060 [get_ports {analog_io[14]}]
set_load -pin_load 0.0060 [get_ports {analog_io[13]}]
set_load -pin_load 0.0060 [get_ports {analog_io[12]}]
set_load -pin_load 0.0060 [get_ports {analog_io[11]}]
set_load -pin_load 0.0060 [get_ports {analog_io[10]}]
set_load -pin_load 0.0060 [get_ports {analog_io[9]}]
set_load -pin_load 0.0060 [get_ports {analog_io[8]}]
set_load -pin_load 0.0060 [get_ports {analog_io[7]}]
set_load -pin_load 0.0060 [get_ports {analog_io[6]}]
set_load -pin_load 0.0060 [get_ports {analog_io[5]}]
set_load -pin_load 0.0060 [get_ports {analog_io[4]}]
set_load -pin_load 0.0060 [get_ports {analog_io[3]}]
set_load -pin_load 0.0060 [get_ports {analog_io[2]}]
set_load -pin_load 0.0060 [get_ports {analog_io[1]}]
set_load -pin_load 0.0060 [get_ports {analog_io[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[71]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[70]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[69]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[68]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[67]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[66]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[65]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[64]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[63]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[62]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[61]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[60]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[59]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[58]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[57]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[56]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[55]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[54]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[53]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[52]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[51]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[50]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[49]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[48]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[47]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[46]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[45]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[44]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[43]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[42]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[41]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[40]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[39]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[38]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[37]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[36]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[35]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[34]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[33]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[32]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[31]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[30]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[29]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[28]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[27]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[26]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[25]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[24]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[23]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[22]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[21]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[20]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[19]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[18]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[17]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[16]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[15]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[14]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[13]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[12]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[11]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[10]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[9]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[8]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[7]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {analog_io[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 10.0000 [current_design]
